### PR TITLE
When body is missing, the process stops and no messages i imported to…

### PR DESCRIPTION
**Pull request by mikkeljohnsen**
… MantisBT

### CODE REVIEW

**Comment by SL-Gundam** [comment]
I would have preferred this (or something like that): $p[ 'body' ] = ( (isset($part->body)) ? $part->body : NULL );

But far more important is why was the body empty? Is it email content which needs a different parsing method?

Is it possible you provide me with a raw_msg debug file so that i can see what the best solution is

**Comment by mikkeljohnsen** [comment]
As I remember it, it happens when the email subject is missing.

**Comment by SL-Gundam** [comment]
Any change you can provide a raw_msg of the content where this happens?

**Comment by SL-Gundam** [comment]
Thank you

**Pull request merged**
