### PR TITLE
If the inline part have a MIME type, set extention according to it.

### PR DESCRIPTION
**Pull request by sadortun**
If the inline part have a MIME type, set extension according to it. This allow preview in the browser, and thumbs for inline images

### CODE REVIEW

**Comment by SL-Gundam** [comment]
Why would this be needed? Nearly all attachments will have a filename defined. This piece of code is only meant for situations where a filename was not defined. I've only seen this happen with meeting requests send to Mantis. So personally do not see the use of this just yet

**Comment by sadortun** [comment]
It's usefull when inline images are added to the emails in HTML format. Instead of just adding ".erp" files that mean nothing to the bug viewer, it will add the correct extension to the file.


Currently inline images are displayed  :
0001623_ test with previous inline image handling


With this fork, the result is much better :

0001622_ test with inline images from mime type

**Comment by SL-Gundam** [comment]
I checked this and this is only an issue if you send html only emails. By default i would recommend setting this to mixed so that a plaintext and html version of the email are delivered.

I'm going to check how other mail programs handle this

**Comment by SL-Gundam** [comment]
How about we use the plugin_mime_types variable in config_defaults_inc.php? I believe it adds all the ones we need

What do you think?

**Comment by sadortun** [comment]
It also work with Gmail when you have inline images.

I'll submit a patch later that use the plugin_mime_type variable config_defaults_inc.php

**Comment by SL-Gundam** [comment]
Please also add an appropriate line in the changelog.

**Comment by sadortun** [comment]
@SL-Gundam  Done.

**Comment by SL-Gundam** [comment]
Not really as it was supposed to but i will make those modifications myself

**Pull request merged**
