### PR TITLE
Basic changes for Modern UI

### PR DESCRIPTION
**Pull request by etlam**
Please create a branch for the Modern UI of MantisBT

### CODE REVIEW

**Comment by SL-Gundam** [comment]
What Modern UI?

The functions you've used seem to be non-existent in the current master branch for MantisBT on github

**Comment by LastElb** [comment]
Yes, thats correct.

Modern-UI is a fork of mantis 1.3 (https://github.com/syncguru/mantisbt).

Maybe you can consider opening a new branch for this like https://github.com/mantisbt-plugins/EventLog/ did for mantis 1.3 and mantis with modern ui

**Comment by libregeek** [comment]
@etlam I would suggest forking EmailReporting and apply changes specific to modern-ui. It's better to keep the master compatible only with mantis-1.3 (and not with any other forks)

**Comment by SL-Gundam** [comment]
Thats very nice but why does Modern UI require these changes?

https://github.com/mantisbt/mantisbt/pull/272
It seems MantisBT will in the future incorporate ModernUI but for the moment it's not part of MantisBT stable and therefore will not be supported by us.

LIke @libregeek said. If you must have these changes then fork EmailReporting and do them yourself but there is not advantage for EmailReporting to do this themselves

I will leave this pull request open for further reference in the future if Modern UI becomes part of MantisBT stable

**Comment by SL-Gundam** [comment]
Is there a way to detect whether someone is running modern ui? or the current stable MantisBT 1.3.x?

**Comment by vboctor** [comment]
MantisBT 1.3.0 was just released today, MantisBT 1.3.x releases will be based on the classic UI.  The modern UI is checked into MantisBT master branch and will go out as 2.0.0* releases.  So you can check the MantisBT version.  For other plugins we maintain three branches:

master-1.2.x - typically retired or critical fixes.
master - for 1.3.x release
modern-ui - for 2.x release

See example plugins:
- https://github.com/mantisbt-plugins/Eventlog
- https://github.com/mantisbt-plugins/csv-import

For everyone, please pickup the MantisBT modern UI from mantisbt/master, other forks are no longer maintained.

**Comment by SL-Gundam** [comment]
Thank you @etlam . This has been added to 0.9.3-DEV

**Comment by libregeek** [comment]
@SL-Gundam do we have a branch for 0.9.3-dev? or is this same as the master?

**Comment by SL-Gundam** [comment]
Same as master. Changes have been made that handles some things differently based on the availability on various functions.

It still needs some work for everything to look good but it works atleast

https://github.com/mantisbt-plugins/EmailReporting/commit/4d58a7894762df0fa4cf74c3d1abadc2d8e1596c

**Comment by libregeek** [comment]
Ok, thanks. I will test and report if there are any issues

**Pull request merged**
