### PR TITLE
Enhance mail_remove_replies_after config item to store multiple values 

### PR DESCRIPTION
**Pull request by libregeek**
Refer: http://www.mantisbt.org/bugs/view.php?id=16715

### CODE REVIEW

**Comment by SL-Gundam** [comment]
I'm closing this pull request since its likely the configuration option will be removed if we succeed with the current experimental branch

**Comment by Dimas-sc** [comment]
So with the actual version, is it possible to specify multiple values?

**Comment by SL-Gundam** [comment]
No with the new version we use new code which pulls apart a email into signatures and separate emails. This way a user does not need to decide what separators he wants to cut of the rest of the content.
https://github.com/willdurand/EmailReplyParser

**Comment by Dimas-sc** [comment]
> No with the new version we use new code which pulls apart a email into signatures and separate emails. 

Sorry, with the "new version" do you mean the actual 0.10.1 or the next one? With 0.10.1 I can't strip replies.

**Comment by SL-Gundam** [comment]
0.11.0-DEV which is the one currently in development

You can get it here: https://github.com/mantisbt-plugins/EmailReporting
Click on clone or download

**Comment by Dimas-sc** [comment]
Thx! Tried the new version and replies are still there. It's maybe because our mail client isn't in English locale?

The replies are like this:

imatge

**Comment by SL-Gundam** [comment]
It currently has support for

El DATE, NAME <EMAIL> escribió:
Il DATE, NAME <EMAIL> ha scritto:

Your version slightly differs from these. Will look into adding support for them

**Comment by Dimas-sc** [comment]
That's Spanish and Italian, mine is Catalan. It'd be perfect if you can support it, thx!! :-)

**Comment by SL-Gundam** [comment]
Support has been added. https://github.com/mantisbt-plugins/EmailReporting/commit/a4f5891f02dc23aff0aaa0ede380106a250b136f
Please check whether it works

**Comment by Dimas-sc** [comment]
Yes, thx, it works! 👏

**Pull request closed without merging**
