### PR TITLE
Merge Experimental email reply parser into master

### PR DESCRIPTION
**Pull request by SL-Gundam**
Code is now stable enough for merge into master

### CODE REVIEW

**Comment by libregeek** [comment]
I ran some quick tests with this branch enabled and here are the issues I observed
- The body of forwarded emails are ignored. They are not captured in the description field.
- HTML mails and plain text emails which are created from the scratch are correctly reported.
- If the HTML email has a bulleted list, then the equivalent markdown has an additional line break (I saw this when I edit the description).

I can provide the email content (saved as text in mantis) if required.

**Comment by SL-Gundam** [comment]
I noticed a lot of extra linebreaks when trying to edit. These extra linebreaks should not be shown when just viewing the ticket.
These are a consequence of the html2markdown conversion.
I felt since these extra linebreaks are only visible while editing, it is not a big issue to worry about.
On the other hand if you see this extra linebreak while normally viewing the issue then it should be fixed. If this is the case please provide the email content

Should we only remove replies/signatures for notes or also for the description? or should we add more config options?

**Comment by libregeek** [comment]
I agree with you on the line breaks. They are not visible when viewing the issues in Mantis.

I think we should only remove the replies and signatures for notes. I'm not sure what other config options we should have.

BTW, did you look at why forwarded and reply email are truncated? Is there any config options which I should enable/disable?

**Comment by SL-Gundam** [comment]
Made the adjustment as suggested
This was the cause for your issue with forwards and replies

In 0.10.x
- signatures were removed from issues and notes, now only from notes
- Replies were only removed from notes. This has been restored.

**Comment by libregeek** [comment]
Thanks. I tested it and both the test cases passed. I think we can go for a beta and get feedback from others.

**Pull request merged**
